# Generated by Django 3.0 on 2020-02-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Democracy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='comment',
            field=models.TextField(default='comment here'),
        ),
    ]
